[Service]
Environment=FOUR_AUTH_FILE=/srv/four-game-data/accounts.json
Environment=FOUR_STATS_FILE=/srv/four-game-data/statistics.sqlite
Environment=HOST=127.0.0.1
Environment=FOUR_PUBLIC_URL=https://4inrow.ru
Environment="FOUR_MAIL_FROM=FOUR³ <no-reply@4inrow.ru>"
UMask=0077
